language: java
sudo: false # faster builds

install: mvn clean install -DskipTests

script: mvn clean verify

jdk:
  - oraclejdk8

before_install:
    - pip install --user codecov

after_success:
    - codecov
